<?binding.jca UpdBpmWfReadyFlag_db.jca?>
<wsdl:definitions name="UpdBpmWfReadyFlag" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/GrnApprovalWorkflow/GrnApproval/UpdBpmWfReadyFlag" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/UpdBpmWfReadyFlag" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/GrnApprovalWorkflow/GrnApproval/UpdBpmWfReadyFlag" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="UpdBpmWfReadyFlag_plt">
        <plt:role name="UpdBpmWfReadyFlag_role">
            <plt:portType name="tns:UpdBpmWfReadyFlag_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/UpdBpmWfReadyFlag" schemaLocation="xsd/UpdBpmWfReadyFlag_sp.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:portType name="UpdBpmWfReadyFlag_ptt">
        <wsdl:operation name="UpdBpmWfReadyFlag">
            <wsdl:input message="tns:args_in_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
